baseURL = 'https://docs.thnikk.moe'
locale = 'en-us'
title = 'Docs'
enableGitInfo = true

[pagination]
  pagersize = 8

[taxonomies]
  tag = "tags"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  [params.navbar]
    displayTitle = false
    displayLogo = true
    [params.navbar.logo]
      link = "https://www.thnikk.moe"
