baseURL = 'https://thnikk.github.io/docs-2026'
locale = 'en-us'
title = 'thnikk'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  [params.navbar]
    displayTitle = true
    displayLogo = true
  [params.search]
    enable = true

[[menu.main]]
  name = "GitHub"
  weight = 2
  url = "https://github.com/thnikk"
